package com.helix.console.engine.dto;

import lombok.Data;

import javax.validation.constraints.NotBlank;
import javax.validation.constraints.NotNull;
import java.io.Serializable;
import java.math.BigDecimal;
import java.util.List;

/**
 * Save request for a single node. The frontend calls it on node:change:data / drag end / double-click edit save.
 *
 * <p><b>Partial update semantics</b>: when {@code nodeId} or {@code nodeCode} hits an existing node it is an update,
 * and only explicitly provided fields are overwritten (null means no update).
 * Therefore the required-field validation of {@code nodeName}/{@code nodeType} only applies on creation,
 * which is checked by the Service layer after it determines the operation is a create; not enforced here via annotations.</p>
 */
@Data
public class NodeSaveDTO implements Serializable {

    private static final long serialVersionUID = 1L;

    /** When it hits an existing node it means update; empty on creation */
    private Integer nodeId;

    @NotNull(message = "Version ID must not be empty")
    private Integer versionId;

    /** Required on creation, optional on update (keeps the original value) */
    private String nodeName;

    /** Temporary code generated by the frontend; the server guarantees uniqueness within the version */
    private String nodeCode;

    /** Required on creation, optional on update (keeps the original value) */
    private Integer nodeType;

    private Integer nodeOrder;

    /** Node configuration, arbitrary JSON */
    private Object nodeJson;

    private String nodeScript;

    private BigDecimal nodeX;

    private BigDecimal nodeY;

    /**
     * Codes of downstream nodes.
     *
     * <p>Note: this must <b>not</b> be initialized to an empty collection. The server performs field-level
     * partial updates with the rule "null means not provided, empty collection means explicitly clear";
     * if it defaulted to an empty collection, a caller updating only some properties would also clear
     * the fields it did not pass (this once caused next_nodes to be cleared when only binding list DBs,
     * breaking the decision flow).</p>
     */
    private List<String> nextNodes;

    /** Knowledge base ids referenced by the node, same semantics as above: null keeps, empty collection clears */
    private List<GraphVO.KnowledgeRef> knowledge;

    /** List DB node: internal list DB ids, same semantics as above */
    private List<Integer> innerListDbs;

    /** List DB node: external list DB ids, same semantics as above */
    private List<Integer> outerListDbs;
}
